"""dump dim_venue from duckdb into a d1 seed file (infra/d1/seed.sql).

writes a DELETE + batched INSERTs you can load with:
    wrangler d1 execute niklo --local --file=../infra/d1/seed.sql
(swap --local for --remote once the d1 db exists in your cloudflare account.)

usage:  uv run python export_to_d1.py
"""

from __future__ import annotations

import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DUCKDB_PATH = os.environ.get(
    "NIKLO_DUCKDB", os.path.normpath(os.path.join(HERE, "warehouse.duckdb"))
)
SEED_PATH = os.path.normpath(os.path.join(HERE, "..", "infra", "d1", "seed.sql"))

# columns in d1's venues table, in order
COLUMNS = [
    "venue_id", "name", "slug", "subcategory_slug", "subcategory_name",
    "category_slug", "category_name", "subcategories", "category_slugs",
    "google_category", "rating", "review_count",
    "latitude", "longitude", "area", "address", "city", "price_level",
    "website", "phone", "hours", "photo_url", "photos", "google_url",
    "status", "is_open", "source_query", "last_verified",
]


def sql_literal(val) -> str:
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "1" if val else "0"
    if isinstance(val, (int, float)):
        return repr(val)
    if isinstance(val, (dict, list)):
        val = json.dumps(val, ensure_ascii=False)
    s = str(val).replace("'", "''")
    return f"'{s}'"


def cached_photo_url(key: str, photo_base: str) -> str:
    base = photo_base.rstrip("/")
    return f"{base}/{key}" if base else f"/{key}"


def bundled_photo_keys(photo_root: str) -> dict[str, str]:
    """Return every downloaded local image keyed by its Google place id."""
    root = os.path.abspath(photo_root)
    if not os.path.isdir(root):
        return {}
    return {
        os.path.splitext(filename)[0]: f"venues/{filename}"
        for filename in os.listdir(root)
        if os.path.isfile(os.path.join(root, filename))
        and os.path.splitext(filename)[1].lower() in {".jpg", ".jpeg", ".png", ".webp"}
    }


def apply_cached_photos(
    rows: list[list], manifest_path: str, photo_base: str, photo_root: str | None = None
) -> tuple[int, int]:
    """Expose only downloaded, Niklo-managed image paths in public data."""
    manifest = {}
    if os.path.exists(manifest_path):
        with open(manifest_path, newline="", encoding="utf-8") as f:
            manifest = {r["venue_id"]: r["key"] for r in csv.DictReader(f)}

    # Local builds are served straight from web/public. A manifest can be rebuilt
    # at any time, so retain every bundled file while it is catching up.
    if photo_base.rstrip("/") == "":
        bundled_root = photo_root or os.path.join(HERE, "..", "web", "public", "venues")
        bundled = bundled_photo_keys(bundled_root)
        bundled.update(manifest)
        manifest = bundled

    venue_index = COLUMNS.index("venue_id")
    photo_index = COLUMNS.index("photo_url")
    photos_index = COLUMNS.index("photos")
    cached = 0
    for row in rows:
        key = manifest.get(row[venue_index])
        row[photos_index] = "[]"  # Keep source gallery URLs out of public D1 data.
        if key:
            row[photo_index] = cached_photo_url(key, photo_base)
            cached += 1
        else:
            row[photo_index] = None
    return cached, len(rows) - cached


def write_seed(rows: list[list], seed_path: str) -> None:
    collist = ", ".join(COLUMNS)
    lines = [
        "-- generated by export_to_d1.py -- do not edit by hand",
        "PRAGMA foreign_keys=OFF;",
        "DELETE FROM venues;",
    ]
    for i in range(0, len(rows), 50):
        chunk = rows[i : i + 50]
        values = ",\n".join(
            "  (" + ", ".join(sql_literal(v) for v in row) + ")" for row in chunk
        )
        lines.append(f"INSERT INTO venues ({collist}) VALUES\n{values};")
    with open(seed_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main() -> None:
    import duckdb

    con = duckdb.connect(DUCKDB_PATH, read_only=True)
    rows = [list(r) for r in con.execute(
        f"select {', '.join(COLUMNS)} from main.dim_venue order by venue_id"
    ).fetchall()]

    # Public data must never hotlink Maps images. All served files are bundled
    # under web/public/venues and deployed with the app.
    manifest = os.path.normpath(os.path.join(HERE, "..", "data", "photo_manifest.csv"))
    cached, missing = apply_cached_photos(rows, manifest, "/")
    print(f"serving {cached} downloaded photos; {missing} fall back to gradient")

    write_seed(rows, SEED_PATH)

    print(f"wrote {len(rows)} venues -> {SEED_PATH}")


if __name__ == "__main__":
    main()
