"""dump dim_venue from duckdb into a d1 seed file (infra/d1/seed.sql).

writes a DELETE + batched INSERTs you can load with:
    wrangler d1 execute niklo --local --file=../infra/d1/seed.sql
(swap --local for --remote once the d1 db exists in your cloudflare account.)

usage:  uv run python export_to_d1.py
"""

from __future__ import annotations

import csv
import json
import os

import duckdb

HERE = os.path.dirname(os.path.abspath(__file__))
DUCKDB_PATH = os.environ.get(
    "NIKLO_DUCKDB", os.path.normpath(os.path.join(HERE, "warehouse.duckdb"))
)
SEED_PATH = os.path.normpath(os.path.join(HERE, "..", "infra", "d1", "seed.sql"))

# columns in d1's venues table, in order
COLUMNS = [
    "venue_id", "name", "slug", "subcategory_slug", "subcategory_name",
    "category_slug", "category_name", "google_category", "rating", "review_count",
    "latitude", "longitude", "area", "address", "city", "price_level",
    "website", "phone", "hours", "photo_url", "photos", "google_url",
    "status", "is_open", "source_query", "last_verified",
]


def sql_literal(val) -> str:
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "1" if val else "0"
    if isinstance(val, (int, float)):
        return repr(val)
    if isinstance(val, (dict, list)):
        val = json.dumps(val, ensure_ascii=False)
    s = str(val).replace("'", "''")
    return f"'{s}'"


def main() -> None:
    con = duckdb.connect(DUCKDB_PATH, read_only=True)
    collist = ", ".join(COLUMNS)
    rows = [list(r) for r in con.execute(
        f"select {collist} from main.dim_venue order by venue_id"
    ).fetchall()]

    # if photos have been mirrored to r2, serve those permanent urls instead of
    # google's temporary cdn links (see photos.py). no-op until R2_PUBLIC_BASE is set.
    photo_base = os.environ.get("R2_PUBLIC_BASE")
    manifest = os.path.normpath(os.path.join(HERE, "..", "data", "photo_manifest.csv"))
    if photo_base and os.path.exists(manifest):
        mirrored = {r["venue_id"]: r["key"] for r in csv.DictReader(open(manifest))}
        vi, pi = COLUMNS.index("venue_id"), COLUMNS.index("photo_url")
        swapped = 0
        for row in rows:
            if row[vi] in mirrored:
                row[pi] = f"{photo_base.rstrip('/')}/{mirrored[row[vi]]}"
                swapped += 1
        print(f"using r2 photos for {swapped} venues")

    lines = [
        "-- generated by export_to_d1.py -- do not edit by hand",
        "PRAGMA foreign_keys=OFF;",
        "DELETE FROM venues;",
    ]
    for i in range(0, len(rows), 50):
        chunk = rows[i : i + 50]
        values = ",\n".join(
            "  (" + ", ".join(sql_literal(v) for v in row) + ")" for row in chunk
        )
        lines.append(f"INSERT INTO venues ({collist}) VALUES\n{values};")

    with open(SEED_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {len(rows)} venues -> {SEED_PATH}")


if __name__ == "__main__":
    main()
