"""flag padel venues that look like bad imports from maps, for manual review.

reads dim_venue (joined to raw for the full category list) and writes:
  - data/padel_flags.csv      machine-readable flags (source of truth)
  - infra/d1/flags.sql        UPDATEs to stamp review_level/review_flag onto d1

signals:
  - shop / supplier / builder categories          -> high   (not a bookable court)
  - other-sport / non-court categories            -> high
  - no rating AND no reviews                       -> check  (junk listing or brand new)
  - generic sports club/complex, no padel signal  -> check
keeps everything else (real padel courts).

usage:  uv run python flag_venues.py
re-apply to d1 after: wrangler d1 execute niklo --local --file=../infra/d1/flags.sql
"""

from __future__ import annotations

import csv
import json
import os
import re

import duckdb

HERE = os.path.dirname(os.path.abspath(__file__))
DUCKDB = os.path.normpath(os.path.join(HERE, "warehouse.duckdb"))
FLAGS_CSV = os.path.normpath(os.path.join(HERE, "..", "data", "padel_flags.csv"))
FLAGS_SQL = os.path.normpath(os.path.join(HERE, "..", "infra", "d1", "flags.sql"))

STORE = ["store", "shop", "wholesaler", "supplier", "flooring", "turf",
         "construction", "retail", "sporting goods", "accessories", "equipment"]
OTHER_SPORT = ["tennis", "squash", "futsal", "cricket", "swimming", "gym",
               "fitness", "snooker", "billiards"]
NONCOURT = ["park", "playground", "amusement", "wedding", "school", "association",
            "organization", "federation", "restaurant", "hotel"]
GENERIC = ["sports club", "sports complex", "club", "stadium", "arena", "sports"]


def hasw(blob: str, words: list[str]) -> bool:
    return any(re.search(r"\b" + re.escape(w) + r"\b", blob) for w in words)


def classify(name, gcat, cats, rating, reviews):
    name = (name or "").lower()
    cats = [c.lower() for c in cats if c]
    blob = " ".join(cats) + " " + name
    empty = (not rating) and (not reviews)

    if hasw(blob, STORE):
        return ("high", "looks like a shop / supplier / builder, not a bookable court")
    # empty listings get flagged even if google calls them a padel court
    if empty:
        return ("check", "no rating or reviews, verify it is a real open court (or a junk listing)")
    if any("padel" in c for c in cats):
        return (None, None)
    if "padel" in name or "paddle" in name:
        return (None, None)
    if hasw(blob, NONCOURT):
        return ("high", f'category "{gcat}", no padel signal')
    if hasw(blob, OTHER_SPORT):
        return ("high", f"looks like a {gcat.lower()} (other sport), no padel signal")
    if hasw(blob, GENERIC):
        return ("check", f'generic "{gcat}", padel not confirmed in name or category')
    return ("check", f'unclear ("{gcat}"), no padel signal')


def main() -> None:
    con = duckdb.connect(DUCKDB, read_only=True)
    rows = con.execute("""
      with one_raw as (
        select place_id, any_value(categories) as categories
        from raw.venues where place_id is not null group by place_id
      )
      select d.venue_id, d.name, d.slug, d.google_category, d.rating, d.review_count,
             r.categories
      from main.dim_venue d left join one_raw r on d.venue_id = r.place_id
      where d.subcategory_slug = 'padel'
    """).fetchall()

    flags = []
    for venue_id, name, slug, gcat, rating, reviews, cats_json in rows:
        cats = [gcat or ""]
        try:
            cats += json.loads(cats_json) if cats_json else []
        except Exception:
            pass
        level, reason = classify(name, gcat, cats, rating, reviews)
        if level:
            flags.append((venue_id, slug, name, level, reason))

    flags.sort(key=lambda f: (0 if f[3] == "high" else 1, f[2].lower()))

    with open(FLAGS_CSV, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["venue_id", "slug", "name", "level", "reason"])
        w.writerows(flags)

    def esc(s):
        return (s or "").replace("'", "''")

    lines = [
        "-- review flags for padel venues (generated by flag_venues.py).",
        "-- re-apply after a re-seed. clear: UPDATE venues SET review_level=NULL, review_flag=NULL;",
        "UPDATE venues SET review_level=NULL, review_flag=NULL WHERE subcategory_slug='padel';",
    ]
    for venue_id, _slug, _name, level, reason in flags:
        lines.append(
            f"UPDATE venues SET review_level='{level}', review_flag='{esc(reason)}' "
            f"WHERE venue_id='{venue_id}';"
        )
    open(FLAGS_SQL, "w").write("\n".join(lines) + "\n")

    high = sum(1 for f in flags if f[3] == "high")
    print(f"flagged {len(flags)} / {len(rows)} padel venues ({high} high, {len(flags) - high} check)")


if __name__ == "__main__":
    main()
