name: niklo
version: "0.1.0"
profile: niklo
config-version: 2

model-paths: ["models"]

models:
  niklo:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
