-- review flags for padel venues (generated by flag_venues.py).
-- re-apply after a re-seed. clear: UPDATE venues SET review_level=NULL, review_flag=NULL;
UPDATE venues SET review_level=NULL, review_flag=NULL WHERE subcategory_slug='padel';
